import { lazy } from 'react';
import type { EffectEntry } from '../../types';

export const OVERLAYS_CATALOG: EffectEntry[] = [
  {
    meta: {
      id: 'overlays-modal-iris-reveal',
      name: 'ModalIrisReveal',
      category: 'overlays',
      sourceWebsite: 'shopify-editions',
      sourceFiles: ['body_html.ts (View-Transition-Morph-Ästhetik)', 'KRANK/src/index.css (stroke-dash Border-Trace)'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Detail-Dialoge', 'Unlock-/Bestätigungs-Momente'],
      performanceNotes: 'clip-path circle + eine SVG-Trace — günstig.',
      mobileNotes: 'Mobiletauglich; Iris-Ursprung = Touch-Punkt.',
      reducedMotionNotes: 'Modal erscheint ohne Iris/Trace, direkt offen.',
      description: 'Modal öffnet als Iris vom Klickpunkt (clip-path circle wächst), Backdrop blurt choreografiert ein, ein Border-Trace umläuft das Panel nach dem Andocken, Content staggert. ESC/Backdrop schließt.',
      importPath: '@/motion-arsenal/effects/overlays/ModalIrisReveal',
      usageJsx: '<ModalIrisReveal accent="#C93030" blurBackdrop={8} />',
      props: [
        { key: 'speed', label: 'Speed', type: 'range', default: 1, min: 0.4, max: 2, step: 0.1 },
        { key: 'accent', label: 'Accent', type: 'color', default: '#C93030' },
        { key: 'blurBackdrop', label: 'Backdrop Blur', type: 'range', default: 8, min: 0, max: 18, step: 1 },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./ModalIrisReveal')),
  },
  {
    meta: {
      id: 'overlays-glass-sheet',
      name: 'GlassSheetOverlay',
      category: 'overlays',
      sourceWebsite: 'shopify-editions',
      sourceFiles: ['shopify.css (Glass-Nav: rgba + backdrop-filter blur + blend)', 'KRANK/src/index.css (Overshoot-Settle)'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Mobile Bottom-Sheets', 'Settings-/Info-Panels', 'Filter-Drawer'],
      performanceNotes: 'backdrop-filter ist die Hauptlast — Fläche klein halten, blur ≤ 16px.',
      mobileNotes: 'Bottom-Sheet ist das native Mobile-Pattern; Drag-Indikator atmet.',
      reducedMotionNotes: 'Sheet erscheint ohne Feder-Einlauf.',
      description: 'Bottom-/Side-Sheet aus geschichtetem Glas: backdrop-blur, Innen-Gradient, Licht-Refraktionskante oben und Noise — federnder outBack-Einlauf, atmender Drag-Indikator, choreografierter Backdrop.',
      importPath: '@/motion-arsenal/effects/overlays/GlassSheetOverlay',
      usageJsx: "<GlassSheetOverlay side=\"bottom\" blur={14} />",
      props: [
        { key: 'side', label: 'Side', type: 'select', default: 'bottom', options: ['bottom', 'right'] },
        { key: 'blur', label: 'Blur', type: 'range', default: 14, min: 4, max: 24, step: 1 },
        { key: 'accent', label: 'Accent', type: 'color', default: '#d4a24a' },
        { key: 'speed', label: 'Speed', type: 'range', default: 1, min: 0.4, max: 2, step: 0.1 },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./GlassSheetOverlay')),
  },
  {
    meta: {
      id: 'overlays-toast-stack-slide',
      name: 'ToastStackSlide',
      displayName: 'Toast Stack Slide',
      category: 'overlays',
      sourceWebsite: 'nox-original',
      sourceFiles: ['NOX Overlays DNA', 'Stacked-Toast-Muster'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Statusmeldungen in Anwendungen und Dashboards', 'Bestaetigungen nach Formularaktionen', 'Fehler- und Systemhinweise ohne Modal'],
      performanceNotes: 'JS haelt nur den Stapelzustand, die Bewegung liegt in CSS-Transitions - kein rAF. Der Fortschrittsbalken ist eine scaleX-Animation mit der Lebensdauer als Dauer, laeuft also ohne Timer-Ticks.',
      mobileNotes: 'Stapelbreite skaliert prozentual, Schliessen-Button mit ausreichendem Touch-Target.',
      reducedMotionNotes: 'Meldungen erscheinen und verschwinden ohne Slide; Fortschritt und Lebensdauer bleiben unveraendert.',
      description: 'Benachrichtigungen fahren seitlich ein und schieben die aelteren per Perspektive in die Tiefe. Der Stapel ist eine aria-live-Region, neue Meldungen werden also vorgelesen, ohne den Fokus zu stehlen.',
      importPath: '@/motion-arsenal/effects/overlays/ToastStackSlide',
      usageJsx: '<ToastStackSlide position="top-right" duration={4200} maxStack={4} />',
      props: [
        { key: 'position', label: 'Position', type: 'select', default: 'top-right', options: ['top-right', 'top-left', 'bottom-right'], group: 'Layout' },
        { key: 'maxStack', label: 'Max Stack', type: 'range', default: 4, min: 1, max: 6, step: 1, group: 'Layout' },
        { key: 'variant', label: 'Typ', type: 'select', default: 'success', options: ['success', 'error', 'info'], group: 'Content' },
        { key: 'duration', label: 'Lebensdauer ms', type: 'range', default: 4200, min: 1500, max: 10000, step: 100, group: 'Motion' },
        { key: 'showProgress', label: 'Fortschritt', type: 'boolean', default: true, group: 'Motion' },
        { key: 'color', label: 'Akzent', type: 'color', default: '#d4a24a', group: 'Color' },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./ToastStackSlide')),
  },
];
