import { lazy } from 'react';
import type { EffectEntry } from '../../types';

export const BACKGROUNDS_CATALOG: EffectEntry[] = [
  {
    meta: {
      id: 'bg-nox-starfield-drift',
      name: 'NoxStarfieldDrift',
      displayName: 'NOX Starfield Drift',
      category: 'backgrounds',
      sourceWebsite: 'nox-original',
      sourceFiles: [
        'noxlabs-site-work/src/components/cosmic/CosmicStage.tsx (3D-Sterne, Zentralprojektion, DPR-/Viewport-Tiers)',
        'noxlabs-site-work/src/lib/journey.ts (Scroll-gekoppelte Live-Dramaturgie; im ruhigen Preset bewusst entkoppelt)',
      ],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Premium-Sci-Fi-Sections', 'Journey-Bereiche', 'Hero-/CTA-Flächen mit Text-Overlay'],
      performanceNotes:
        'Ein Canvas2D-Loop, O(n), DPR im gemeinsamen Canvas-Hook auf 2 begrenzt. Das Preset deckelt automatisch auf 320 Sterne unter 560 px und 440 Sterne unter 900 px; Hintergrund-Tabs pausieren.',
      mobileNotes:
        'Mobil automatisch reduzierte Sternzahl, keine Pointer-Abhängigkeit und keine Warp-Streaks. Die dunkle Text-Safe-Zone bleibt in allen Größen erhalten.',
      reducedMotionNotes:
        'Ein statischer, deterministischer Sternenhimmel wird einmal gerendert; Drift und Twinkle laufen nicht.',
      description:
        'Subtiler kosmischer Hintergrund mit sanft bewegten Sternen für Premium-Sci-Fi-Sections und Journey-Bereiche. Ruhige Standardfassung des NOX-CosmicStage-Sternenfelds: keine aggressiven Warp-Streaks, keine hektische Vorwärtsbewegung und eine abgedunkelte Mitte für gut lesbare Text-Overlays.',
      currentUsage: [
        'NOX-Startseite: fixer CosmicStage-Hintergrund hinter der durchgehenden Scroll-Journey',
        'Journey-Phasen vom Mondaufbruch bis zum Event-Horizon-CTA',
      ],
      technicalBasis:
        'Canvas2D mit deterministischen 3D-Sternkoordinaten, Zentralprojektion, z-Recycling und eigener requestAnimationFrame-Logik über den Arsenal-Canvas-Hook; kein CSS-/GSAP-/WebGL-Effekt.',
      importPath: '@/motion-arsenal/effects/backgrounds/NoxStarfieldDrift',
      usageJsx:
        '<NoxStarfieldDrift starCount={520} driftSpeed={0.055} intensity={0.62} depth={0.72} twinkle={0.12} textSafety={0.68} />',
      props: [
        { key: 'starCount', label: 'Stars', type: 'range', default: 520, min: 120, max: 1000, step: 20 },
        { key: 'driftSpeed', label: 'Drift Speed', type: 'range', default: 0.055, min: 0, max: 0.18, step: 0.005 },
        { key: 'intensity', label: 'Intensity', type: 'range', default: 0.62, min: 0.2, max: 1, step: 0.02 },
        { key: 'depth', label: 'Depth', type: 'range', default: 0.72, min: 0.35, max: 1, step: 0.02 },
        { key: 'twinkle', label: 'Twinkle', type: 'range', default: 0.12, min: 0, max: 0.35, step: 0.01 },
        { key: 'textSafety', label: 'Text Safety', type: 'range', default: 0.68, min: 0, max: 1, step: 0.02 },
      ],
      productionSafe: true,
      status: 'production-safe',
      fullBleed: true,
    },
    Component: lazy(() => import('./NoxStarfieldDrift')),
  },
  {
    meta: {
      id: 'bg-nox-scribble-field',
      name: 'NoxAdaptedScribbleField',
      category: 'backgrounds',
      sourceWebsite: 'oryzo-screenshot',
      sourceFiles: ['ORYZO-Referenz (Farb-/Layer-Klasse)', 'KRANK/src/hoisted.js (Layering: eine Physik-Quelle)', 'KRANK/src/index.css (stroke-dash Draw-Mechanik)'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['NOX Forge Hero', 'Premium-Landingpage-Hintergrund', 'Section-Atmosphäre hinter Typo'],
      performanceNotes: 'SVG-Blur auf bis zu 14 Layern — Density auf schwacher Hardware senken. Kein Canvas, kein WebGL.',
      mobileNotes: 'Density ≤ 6 empfohlen; Parallax entfällt ohne Pointer (bleibt ruhig-statisch).',
      reducedMotionNotes: 'Drift/Draw aus, statisches Scribble-Feld mit Glow bleibt.',
      description:
        'NOX-Produktionsvariante der ORYZO-Klasse: prozedurale Ember-/Gold-Scribbles mit Blur-Glow-Kopie, mix-blend-screen, organischem Drift, stroke-dash Draw-on — plus echte Pointer-Proximity-Energie: jedes Scribble färbt sich, glüht, verdickt und driftet, wenn der Pointer nah ist, und glimmt danach langsam ab. Symbolset via Registry austauschbar.',
      importPath: '@/motion-arsenal/effects/backgrounds/NoxAdaptedScribbleField',
      usageJsx: "<NoxAdaptedScribbleField colorMode=\"nox\" intensity={0.8} density={7} parallax={0.5} proximityRadius={200} />",
      props: [
        { key: 'colorMode', label: 'Color Mode', type: 'select', default: 'nox', options: ['nox', 'ember', 'mono'] },
        { key: 'intensity', label: 'Intensity', type: 'range', default: 0.8, min: 0.2, max: 1, step: 0.05 },
        { key: 'speed', label: 'Speed', type: 'range', default: 1, min: 0.2, max: 3, step: 0.1 },
        { key: 'density', label: 'Density', type: 'range', default: 7, min: 3, max: 14, step: 1 },
        { key: 'blur', label: 'Blur', type: 'range', default: 14, min: 4, max: 30, step: 1 },
        { key: 'rotation', label: 'Rotation', type: 'range', default: 16, min: 0, max: 45, step: 1 },
        { key: 'parallax', label: 'Parallax', type: 'range', default: 0.5, min: 0, max: 1, step: 0.05 },
        { key: 'proximityRadius', label: 'Proximity Radius', type: 'range', default: 200, min: 60, max: 360, step: 10 },
        { key: 'blendMode', label: 'Blend', type: 'select', default: 'screen', options: ['screen', 'lighten', 'plus-lighter', 'normal'] },
      ],
      productionSafe: true,
      fullBleed: true,
    },
    Component: lazy(() => import('./NoxAdaptedScribbleField')),
  },
  {
    meta: {
      id: 'bg-forge-energy-glyphs',
      name: 'ForgeEnergyGlyphs',
      category: 'backgrounds',
      sourceWebsite: 'nox-original',
      sourceFiles: ['KRANK/src/index.css (@keyframes grip-instruction-wheel-dash — stroke-dash Mechanik)', 'ORYZO-Referenz (Symbol-Layer-Klasse)'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['NOX Forge (Rank/Black Forge)', 'Dashboard-Hintergrund', 'System-/Tech-Sektionen'],
      performanceNotes: 'Reine CSS-Animationen auf SVG-Pfaden; Blur-Kopien sind die Hauptlast — glyphCount ≤ 12 auf Mid-Range.',
      mobileNotes: 'glyphCount ≤ 8; Parallax entfällt ohne Pointer.',
      reducedMotionNotes: 'Zünd-Zyklen aus, Glyphen statisch schwach glimmend.',
      description:
        'Hand-gezeichnete NOX-Runen als einzelne Energieobjekte: Pointer-Nähe entzündet eine Glyphe — sie zeichnet sich proportional zur Nähe (stroke-dash), färbt sich von gedämpft zu Ember/Gold/Rot, glüht auf und glimmt langsam nach. Ohne Pointer atmet ein feiner Ambient-Puls. Rune-Set via `glyphSet`/`symbols` austauschbar.',
      importPath: '@/motion-arsenal/effects/backgrounds/ForgeEnergyGlyphs',
      usageJsx: "<ForgeEnergyGlyphs glyphCount={10} color=\"#d4a24a\" glyphSet=\"nox-runes\" proximityRadius={170} />",
      props: [
        { key: 'glyphCount', label: 'Glyphs', type: 'range', default: 10, min: 4, max: 18, step: 1 },
        { key: 'color', label: 'Color', type: 'color', default: '#d4a24a' },
        { key: 'glyphSet', label: 'Glyph Set', type: 'select', default: 'nox-runes', options: ['nox-runes', 'procedural'] },
        { key: 'proximityRadius', label: 'Ignite Radius', type: 'range', default: 170, min: 60, max: 340, step: 10 },
        { key: 'parallax', label: 'Parallax', type: 'range', default: 0.45, min: 0, max: 1, step: 0.05 },
        { key: 'intensity', label: 'Intensity', type: 'range', default: 0.9, min: 0.2, max: 1, step: 0.05 },
      ],
      productionSafe: true,
      fullBleed: true,
    },
    Component: lazy(() => import('./ForgeEnergyGlyphs')),
  },
  {
    meta: {
      id: 'bg-orbital-light-trails',
      name: 'OrbitalLightTrails',
      category: 'backgrounds',
      sourceWebsite: 'active-theory',
      sourceFiles: ['activetheory-bundle.js (Trail-History-Buffer + Decay/Taper, framerateNormalizeLerpAlpha, blendFunc(ONE,ONE))'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Hero-Atmosphäre', 'Loader-/Warte-Screens', 'Agent-Interface-Hintergrund'],
      performanceNotes: 'Canvas2D Line-Strips — sehr günstig. trailLength ≤ 120.',
      mobileNotes: 'Voll touch-tauglich (autonome Orbits, kein Pointer nötig).',
      reducedMotionNotes: 'Loop pausiert, letzter Frame bleibt.',
      description:
        'Autonome Licht-Emitter auf Lissajous-Orbits schreiben additive Trails mit Decay und Breiten-Taper — die Active-Theory-Trail-Mechanik in NOX-Palette (Ember/Gold/Weißglut), atmosphärisch verlangsamt.',
      importPath: '@/motion-arsenal/effects/backgrounds/OrbitalLightTrails',
      usageJsx: '<OrbitalLightTrails orbCount={4} trailLength={60} intensity={0.85} />',
      props: [
        { key: 'orbCount', label: 'Orbs', type: 'range', default: 4, min: 1, max: 8, step: 1 },
        { key: 'trailLength', label: 'Trail Length', type: 'range', default: 60, min: 12, max: 120, step: 4 },
        { key: 'speed', label: 'Speed', type: 'range', default: 1, min: 0.2, max: 3, step: 0.1 },
        { key: 'intensity', label: 'Intensity', type: 'range', default: 0.85, min: 0.2, max: 1, step: 0.05 },
      ],
      productionSafe: true,
      fullBleed: true,
    },
    Component: lazy(() => import('./OrbitalLightTrails')),
  },
  {
    meta: {
      id: 'bg-symbol-storm',
      name: 'BackgroundSymbolStorm',
      category: 'backgrounds',
      sourceWebsite: 'nox-original',
      sourceFiles: ['ORYZO-Referenz (Symbol-Klasse)', 'KRANK/src/hoisted.js (lerp-Strömung, Tiefen-Layering)'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['System-/Daten-Sektionen', 'NOX Forge Test-Hintergrund', '404/Empty-States mit Charakter'],
      performanceNotes: 'Canvas2D, O(n) — bis 120 Symbole flüssig. Kein Filter-Einsatz (Blur via Alpha simuliert).',
      mobileNotes: 'Density ≤ 40; Pointer-Strömung entfällt, Basis-Drift bleibt.',
      reducedMotionNotes: 'Loop pausiert, statisches Symbolfeld.',
      description:
        'Sturm aus kleinen System-Symbolen (Kreuze, Ringe, Dreiecke, Fragmente) in drei Tiefenebenen: vorne schnell + scharf mit Glow-Punch, hinten langsam + schwach. Pointer erzeugt eine gedämpfte Strömungs-Ablenkung.',
      importPath: '@/motion-arsenal/effects/backgrounds/BackgroundSymbolStorm',
      usageJsx: "<BackgroundSymbolStorm density={46} color=\"#C93030\" pointerInfluence={0.6} />",
      props: [
        { key: 'density', label: 'Density', type: 'range', default: 46, min: 10, max: 120, step: 2 },
        { key: 'speed', label: 'Speed', type: 'range', default: 1, min: 0.2, max: 3, step: 0.1 },
        { key: 'color', label: 'Color', type: 'color', default: '#C93030' },
        { key: 'pointerInfluence', label: 'Pointer Flow', type: 'range', default: 0.6, min: 0, max: 1, step: 0.05 },
      ],
      productionSafe: true,
      fullBleed: true,
    },
    Component: lazy(() => import('./BackgroundSymbolStorm')),
  },
  {
    meta: {
      id: 'bg-noise-fog-field',
      name: 'NoiseFogField',
      category: 'backgrounds',
      sourceWebsite: 'krank-lusion',
      sourceFiles: ['KRANK/src/hoisted.js (fbm/Distortion-Pass, getBlueNoise-Grain)', 'activetheory-bundle.js (Fullscreen-Quad-Pattern)'],
      mode: 'nox-adapted',
      complexity: 'high',
      dependencies: [],
      bestFor: ['Premium-Hero-Atmosphäre', 'Black-Forge-Gate', 'Kunden-Sites mit Charakter'],
      performanceNotes: 'Ein WebGL-Fragment-Pass, DPR auf 1.5 gekappt. 5-Oktaven-fbm ×3 pro Pixel — auf Low-End scale erhöhen (weniger Detail nötig).',
      mobileNotes: 'Läuft auf Mobile; Pointer-Wärmeblase entfällt ohne Pointer.',
      reducedMotionNotes: 'Eingefrorener Shader-Frame (frozenTime), kein Loop.',
      description:
        'Domain-warped fbm-Nebel als einzelner WebGL-Pass: mehrschichtiger Rauch mit Ember-Tint, Glut-Kernen in den dichtesten Falten, Pointer-Wärmeblase und Grain gegen Banding — die KRANK-Atmosphäre ohne 1MB-Engine.',
      importPath: '@/motion-arsenal/effects/backgrounds/NoiseFogField',
      usageJsx: '<NoiseFogField intensity={0.9} emberAmount={0.8} scale={2.2} />',
      props: [
        { key: 'intensity', label: 'Intensity', type: 'range', default: 0.9, min: 0.2, max: 1.4, step: 0.05 },
        { key: 'speed', label: 'Speed', type: 'range', default: 1, min: 0.2, max: 3, step: 0.1 },
        { key: 'emberAmount', label: 'Ember', type: 'range', default: 0.8, min: 0, max: 1, step: 0.05 },
        { key: 'scale', label: 'Scale', type: 'range', default: 2.2, min: 1, max: 5, step: 0.1 },
      ],
      productionSafe: true,
      clickToRun: false,
      fullBleed: true,
    },
    Component: lazy(() => import('./NoiseFogField')),
  },
  {
    meta: {
      id: 'bg-depth-glow-stack',
      name: 'DepthGlowLayerStack',
      category: 'backgrounds',
      sourceWebsite: 'krank-lusion',
      sourceFiles: ['KRANK/src/hoisted.js (Gobo-Light-Projection — weiche projizierte Lichtvolumina)'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Ambient-Grundschicht unter anderen Effekten', 'Dashboards', 'lange Content-Seiten (billig!)'],
      performanceNotes: 'Nur CSS-Compositing (blur + screen), kein JS-Loop außer Parallax. Der billigste Atmosphere-Effekt im Arsenal.',
      mobileNotes: 'Uneingeschränkt mobile-tauglich.',
      reducedMotionNotes: 'Drift/Breathe aus; statische Lichtvolumina bleiben.',
      description:
        'Kein einzelner Glow-Kreis: Stapel aus 5-7 unabhängig driftenden, atmenden Licht-Volumina mit pro Ebene eigenem Hue/Blur/Drift + Grain-Overlay + Pointer-Parallax — die Gobo-Lichtflecken-Idee aus dem Lusion-Rendering als reines CSS.',
      importPath: '@/motion-arsenal/effects/backgrounds/DepthGlowLayerStack',
      usageJsx: '<DepthGlowLayerStack layerCount={6} hueMix={0.7} parallax={0.5} />',
      props: [
        { key: 'layerCount', label: 'Layers', type: 'range', default: 6, min: 3, max: 9, step: 1 },
        { key: 'hueMix', label: 'Hue Mix', type: 'range', default: 0.7, min: 0, max: 1, step: 0.05 },
        { key: 'driftSpeed', label: 'Drift', type: 'range', default: 1, min: 0.2, max: 3, step: 0.1 },
        { key: 'parallax', label: 'Parallax', type: 'range', default: 0.5, min: 0, max: 1, step: 0.05 },
        { key: 'intensity', label: 'Intensity', type: 'range', default: 0.85, min: 0.2, max: 1.2, step: 0.05 },
      ],
      productionSafe: true,
      fullBleed: true,
    },
    Component: lazy(() => import('./DepthGlowLayerStack')),
  },
  {
    meta: {
      id: 'bg-radial-beam-atmosphere',
      name: 'RadialBeamAtmosphere',
      category: 'backgrounds',
      sourceWebsite: 'krank-lusion',
      sourceFiles: ['KRANK/src/hoisted.js (Gobo/Lichtkegel-Projektion als Vorbild)'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Hero mit „Erleuchtungs"-Moment', 'Pricing-/CTA-Sektionen', 'Launch-/Countdown-Pages'],
      performanceNotes: 'Zwei rotierende conic-gradients + Maske — GPU-composited, sehr günstig. Große Fläche (240vmax) beachten.',
      mobileNotes: 'Mobile-tauglich; rotationSpeed ≥ 60s halten (Ruhe).',
      reducedMotionNotes: 'Rotation/Puls aus; statischer Strahlenkranz bleibt.',
      description:
        'God-Ray-Atmosphäre: zwei gegenläufig rotierende Strahlenkränze (repeating-conic-gradient) mit radialer Auslauf-Maske, pulsierendem Kern-Glow am Ursprung und Grain — cinematisches Licht ohne WebGL.',
      importPath: '@/motion-arsenal/effects/backgrounds/RadialBeamAtmosphere',
      usageJsx: "<RadialBeamAtmosphere beamCount={9} rotationSpeed={60} color=\"#C93030\" originY={78} />",
      props: [
        { key: 'beamCount', label: 'Beams', type: 'range', default: 9, min: 4, max: 18, step: 1 },
        { key: 'rotationSpeed', label: 'Rotation (s)', type: 'range', default: 60, min: 20, max: 160, step: 5 },
        { key: 'color', label: 'Color', type: 'color', default: '#C93030' },
        { key: 'coreGlow', label: 'Core Glow', type: 'range', default: 0.7, min: 0, max: 1, step: 0.05 },
        { key: 'originY', label: 'Origin Y %', type: 'range', default: 78, min: 20, max: 110, step: 2 },
      ],
      productionSafe: true,
      fullBleed: true,
    },
    Component: lazy(() => import('./RadialBeamAtmosphere')),
  },
  {
    meta: {
      id: 'bg-ember-curl-drift',
      name: 'EmberCurlDrift',
      category: 'backgrounds',
      sourceWebsite: 'krank-lusion',
      sourceFiles: ['KRANK/src/hoisted.js (curl()-Vektorfeld + Particles-Klasse, additive Bloom-Komposition)'],
      mode: 'nox-adapted',
      complexity: 'high',
      dependencies: [],
      bestFor: ['NOX Forge (Schmiede-DNA!)', 'Hard-Mode/Black-Forge-Momente', 'Hero-Unterschicht'],
      performanceNotes: 'Canvas2D additive, O(n) Curl-Auswertung — bis 400 Funken ok, Glow-Höfe nur für heißeste 25%.',
      mobileNotes: 'count ≤ 100 auf Mobile.',
      reducedMotionNotes: 'Loop pausiert; statisches Glut-Bild.',
      description:
        'Schmiede-Funken steigen aus der Glut auf, ein Curl-Noise-Feld verwirbelt sie seitlich, über die Lebenszeit kühlen sie von Weißgold über Orange zu Dunkelrot ab und verlöschen flackernd — die KRANK-Partikel-Mechanik in NOX-Forge-DNA.',
      importPath: '@/motion-arsenal/effects/backgrounds/EmberCurlDrift',
      usageJsx: '<EmberCurlDrift count={140} updraft={1} turbulence={1} />',
      props: [
        { key: 'count', label: 'Sparks', type: 'range', default: 140, min: 30, max: 400, step: 10 },
        { key: 'updraft', label: 'Updraft', type: 'range', default: 1, min: 0.2, max: 2.5, step: 0.1 },
        { key: 'turbulence', label: 'Turbulence', type: 'range', default: 1, min: 0, max: 2.5, step: 0.1 },
        { key: 'speed', label: 'Speed', type: 'range', default: 1, min: 0.2, max: 3, step: 0.1 },
      ],
      productionSafe: true,
      fullBleed: true,
    },
    Component: lazy(() => import('./EmberCurlDrift')),
  },
];
