export const FORGE_ENERGY_GLYPH_CSS = String.raw`
.feg-root{position:absolute;inset:0;overflow:hidden;isolation:isolate;color:#f4f0e8;background:var(--feg-bg);font-family:var(--sans,system-ui,sans-serif)}
.feg-root:before{content:'';position:absolute;inset:0;z-index:0;pointer-events:none;background-image:linear-gradient(rgba(255,255,255,.025) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.025) 1px,transparent 1px);background-size:46px 46px;mask-image:radial-gradient(circle at center,#000,transparent 78%);opacity:.38}
.feg-root:after{content:'';position:absolute;inset:-24%;z-index:12;pointer-events:none;opacity:.045;background-image:url("data:image/svg+xml,%3Csvg viewBox='0 0 180 180' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.74' numOctaves='3' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E");animation:feg-noise .3s steps(2) infinite}@keyframes feg-noise{0%{transform:translate(-2%,-1%)}50%{transform:translate(2%,1%)}100%{transform:translate(-1%,2%)}}
.feg-aura{position:absolute;inset:8%;z-index:1;pointer-events:none;background:radial-gradient(circle at calc(50% + var(--feg-px)*7%),calc(50% + var(--feg-py)*7%),color-mix(in srgb,var(--feg-primary) calc(10% + var(--feg-heat)*18%),transparent),transparent 42%);filter:blur(26px);opacity:calc(.35 + var(--feg-heat)*.35)}
.feg-dust{position:absolute;inset:0;z-index:2;pointer-events:none}.feg-dust span{position:absolute;left:var(--x);top:var(--y);width:var(--s);height:var(--s);border-radius:50%;background:var(--feg-secondary);box-shadow:0 0 8px var(--feg-primary);opacity:var(--o);animation:feg-dust var(--dur) ease-in-out infinite alternate;animation-delay:var(--delay)}@keyframes feg-dust{to{transform:translate3d(var(--dx),var(--dy),0) scale(1.35);opacity:calc(var(--o)*.45)}}
.feg-connectors{position:absolute;inset:0;z-index:3;width:100%;height:100%;pointer-events:none;overflow:visible}.feg-link-base{fill:none;stroke:var(--feg-dim);stroke-width:.24;opacity:calc(.18 + var(--feg-connect)*.24)}.feg-link-flow{fill:none;stroke:var(--feg-primary);stroke-width:.28;stroke-linecap:round;stroke-dasharray:1.4 4.8;opacity:calc(var(--feg-connect)*.72);filter:url(#placeholder);animation:feg-link var(--dur) linear infinite;animation-delay:var(--delay)}@keyframes feg-link{to{stroke-dashoffset:-22}}.feg-link-pulse{fill:var(--feg-hot);opacity:calc(var(--feg-events)*.9);filter:url(#placeholder)}
.feg-field{position:absolute;inset:0;z-index:4;pointer-events:none}.feg-object{position:absolute;left:var(--x);top:var(--y);width:var(--size);aspect-ratio:1;transform:translate(-50%,-50%);mix-blend-mode:screen}.feg-object[data-layer=ambient]{z-index:1;opacity:.56}.feg-object[data-layer=active]{z-index:3;opacity:.88}.feg-object[data-layer=hero]{z-index:6;opacity:1}.feg-parallax,.feg-motion,.feg-energy{position:relative;width:100%;height:100%;transform-origin:50% 50%}.feg-parallax,.feg-energy{will-change:transform}.feg-motion{animation:feg-float var(--float-duration) ease-in-out infinite alternate,feg-rotate var(--rotate-duration) linear infinite;animation-delay:var(--delay),var(--delay)}@keyframes feg-float{to{transform:translate3d(var(--float-x),var(--float-y),0)}}@keyframes feg-rotate{to{rotate:var(--rotate-end)}}
.feg-energy svg{width:100%;height:100%;overflow:visible}.feg-path-glow{fill:none;stroke:var(--glyph-stroke);stroke-width:var(--glyph-glow-width);stroke-linecap:round;stroke-linejoin:round;opacity:var(--glyph-glow-opacity);filter:url(#placeholder)}.feg-path-crisp{fill:none;stroke:var(--glyph-stroke);stroke-width:var(--glyph-width);stroke-linecap:round;stroke-linejoin:round;opacity:var(--glyph-opacity);stroke-dasharray:1;stroke-dashoffset:var(--glyph-dash)}
.feg-object[data-layer=hero] .feg-energy:before{content:'';position:absolute;inset:-14%;border:1px dashed color-mix(in srgb,var(--feg-secondary) 54%,transparent);border-radius:50%;opacity:calc(.12 + var(--glyph-energy)*.65);animation:feg-orbit calc(var(--rotate-duration)*.72) linear infinite reverse}.feg-object[data-layer=hero] .feg-energy:after{content:attr(data-label);position:absolute;left:50%;top:calc(100% + 8px);transform:translateX(-50%);color:color-mix(in srgb,var(--feg-secondary) 72%,white);font:800 5px/1 var(--mono,monospace);letter-spacing:.2em;white-space:nowrap;opacity:calc(.18 + var(--glyph-energy)*.75);text-shadow:0 0 10px var(--feg-primary)}@keyframes feg-orbit{to{transform:rotate(360deg)}}
.feg-event{position:absolute;left:var(--x);top:var(--y);z-index:5;width:var(--size);aspect-ratio:1;border:1px solid var(--feg-secondary);border-radius:50%;pointer-events:none;transform:translate(-50%,-50%) scale(.25);opacity:0;box-shadow:0 0 18px var(--feg-primary),inset 0 0 18px color-mix(in srgb,var(--feg-primary) 18%,transparent);animation:feg-event var(--event-duration) ease-out infinite;animation-delay:var(--delay)}@keyframes feg-event{0%,58%{opacity:0;transform:translate(-50%,-50%) scale(.25)}68%{opacity:calc(var(--feg-events)*.85)}100%{opacity:0;transform:translate(-50%,-50%) scale(1.7)}}
.feg-heat{position:absolute;inset:-12%;z-index:8;pointer-events:none;opacity:calc(var(--feg-distortion)*var(--feg-events)*.22);background:repeating-linear-gradient(0deg,transparent 0 7px,color-mix(in srgb,var(--feg-primary) 15%,transparent) 8px 9px,transparent 10px 17px);mask-image:radial-gradient(circle at center,#000,transparent 72%);filter:blur(3px);animation:feg-heat 4s ease-in-out infinite alternate}@keyframes feg-heat{to{transform:translate3d(1.5%,-1%,0) skewX(-1.5deg) scaleY(1.03)}}.feg-vignette{position:absolute;inset:0;z-index:9;pointer-events:none;background:radial-gradient(circle at 50% 48%,transparent 0 30%,rgba(2,2,3,.22) 64%,rgba(2,2,3,.76) 100%)}
.feg-switcher,.feg-state-switcher{position:absolute;left:14px;right:14px;z-index:30;display:flex;gap:5px;overflow-x:auto;scrollbar-width:none}.feg-switcher{top:13px}.feg-state-switcher{top:47px}.feg-switcher::-webkit-scrollbar,.feg-state-switcher::-webkit-scrollbar{display:none}.feg-switcher button,.feg-state-switcher button{flex:0 0 auto;padding:6px 8px;border:1px solid rgba(255,255,255,.09);background:rgba(6,6,8,.7);color:rgba(255,255,255,.38);font:800 6px/1 var(--mono,monospace);letter-spacing:.14em;cursor:pointer;backdrop-filter:blur(8px);transition:.22s ease}.feg-switcher button:hover,.feg-state-switcher button:hover{color:#fff;border-color:var(--feg-primary);transform:translateY(-1px)}.feg-switcher button[aria-pressed=true],.feg-state-switcher button[aria-pressed=true]{color:#fff;border-color:var(--feg-secondary);background:color-mix(in srgb,var(--feg-primary) 16%,rgba(6,6,8,.88));box-shadow:0 0 12px color-mix(in srgb,var(--feg-primary) 28%,transparent)}
.feg-reference{position:absolute;left:14px;bottom:13px;z-index:30;display:flex;align-items:center;gap:8px;max-width:58%;padding:7px 9px;border-left:1px solid var(--feg-primary);background:rgba(6,6,8,.68);backdrop-filter:blur(8px)}.feg-reference code{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:rgba(255,255,255,.4);font:600 6px/1 var(--mono,monospace)}.feg-reference button{padding:0;border:0;background:none;color:var(--feg-secondary);font:800 6px/1 var(--mono,monospace);letter-spacing:.12em;cursor:pointer}.feg-status{position:absolute;right:14px;bottom:13px;z-index:30;max-width:38%;text-align:right}.feg-status strong{display:block;color:var(--feg-secondary);font:800 8px/1.15 var(--mono,monospace);letter-spacing:.16em;text-shadow:0 0 12px var(--feg-primary)}.feg-status span{display:block;margin-top:5px;color:rgba(255,255,255,.34);font:700 6px/1.35 var(--mono,monospace);letter-spacing:.14em}.feg-root[data-state=stealth] .feg-object[data-layer=ambient]{opacity:.25}.feg-root[data-state=ritual] .feg-object[data-layer=hero] .feg-energy:before{border-style:solid}.feg-root[data-state=overdrive] .feg-link-flow{stroke-width:.4}
@media(prefers-reduced-motion:reduce){.feg-root:after,.feg-dust span,.feg-motion,.feg-link-flow,.feg-object[data-layer=hero] .feg-energy:before,.feg-event,.feg-heat{animation:none!important}.feg-link-pulse{display:none}}
@container(max-width:680px){.feg-switcher,.feg-state-switcher{left:8px;right:8px}.feg-state-switcher{top:45px}.feg-reference{left:8px;bottom:8px;max-width:68%}.feg-status{right:8px;bottom:8px}.feg-object[data-layer=ambient]:nth-child(3n){display:none}}
`;
