import { lazy } from 'react';
import type { EffectEntry } from '../../types';

export const FORMS_CATALOG: EffectEntry[] = [
  {
    meta: {
      id: 'forms-answer-lock-in',
      name: 'AnswerLockIn',
      category: 'forms',
      sourceWebsite: 'krank-lusion',
      sourceFiles: ['KRANK/src/index.css (Overshoot cubic-bezier(.3,0,.66,-.3))', 'stroke-dash Border-Trace'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['NOX Forge NPC-Test', 'Quiz-/Assessment-Funnels', 'Umfragen mit Gewicht'],
      performanceNotes: 'Ein Border-Trace + Transforms pro Auswahl — günstig.',
      mobileNotes: 'Tap-tauglich.',
      reducedMotionNotes: 'Auswahl sofort markiert, kein Settle/Trace.',
      description: 'Antwort-Skala mit mechanischem Lock-In: Auswahl dippt kurz und settlet mit KRANK-Overshoot, ein Border-Trace umläuft die Karte, die LED zündet, nicht gewählte dimmen, eine Energie-Linie verbindet zur Weiter-Aktion.',
      importPath: '@/motion-arsenal/effects/forms/AnswerLockIn',
      usageJsx: '<AnswerLockIn accentColor="#C93030" showEnergyLine />',
      props: [
        { key: 'accentColor', label: 'Accent', type: 'color', default: '#C93030' },
        { key: 'lockDuration', label: 'Lock s', type: 'range', default: 0.6, min: 0.2, max: 1.5, step: 0.05 },
        { key: 'dimOpacity', label: 'Dim', type: 'range', default: 0.4, min: 0.1, max: 0.8, step: 0.05 },
        { key: 'showEnergyLine', label: 'Energy Line', type: 'boolean', default: true },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./AnswerLockIn')),
  },
  {
    meta: {
      id: 'forms-question-transition',
      name: 'QuestionTransition',
      category: 'forms',
      sourceWebsite: 'nox-original',
      sourceFiles: ['Scan-Linien-Kollaps (Eigenbau)', 'Shopify Cascade-Timing (Content-Stagger)'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Mehrstufige Tests/Funnels', 'NOX Forge Frage-Wechsel'],
      performanceNotes: 'scaleY/Blur auf einem Container — günstig.',
      mobileNotes: 'Touch-tauglich.',
      reducedMotionNotes: 'Direkter Frage-Wechsel.',
      description: 'Frage-Wechsel als Scan-Zyklus: alte Frage kollabiert in eine Scan-Linie (scaleY + Blur), die Linie wischt richtungsbewusst zur Seite, die neue Frage expandiert daraus und staggert ihren Content.',
      importPath: '@/motion-arsenal/effects/forms/QuestionTransition',
      usageJsx: "<QuestionTransition direction=\"forward\" autoCycle />",
      props: [
        { key: 'duration', label: 'Duration s', type: 'range', default: 0.9, min: 0.4, max: 2, step: 0.1 },
        { key: 'blurAmount', label: 'Blur', type: 'range', default: 8, min: 0, max: 16, step: 1 },
        { key: 'accentColor', label: 'Accent', type: 'color', default: '#C93030' },
        { key: 'direction', label: 'Direction', type: 'select', default: 'forward', options: ['forward', 'back'] },
        { key: 'autoCycle', label: 'Auto-Cycle', type: 'boolean', default: true },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./QuestionTransition')),
  },
  {
    meta: {
      id: 'forms-validation-pulse',
      name: 'ValidationPulse',
      category: 'forms',
      sourceWebsite: 'nox-original',
      sourceFiles: ['Echte Feder-Physik x = A·e^(-λt)·sin(ωt) statt CSS-Shake (Lusion-Physik-Denken)'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Signup-/Login-Felder', 'Checkout-Formulare', 'Magic-Link-Eingaben'],
      performanceNotes: 'Feder-Sim auf einem Transform — vernachlässigbar.',
      mobileNotes: 'Touch-tauglich.',
      reducedMotionNotes: 'Farb-/Text-Feedback ohne Shake/Ringe.',
      description: 'Eingabefeld mit lebendiger Validierung: Fehler löst eine ECHTE gedämpfte Feder-Schwingung aus (kein CSS-Shake) plus roten Ring nach außen; Erfolg zieht einen grünen Ring nach innen und zeichnet das Häkchen; die Signal-LED atmet beim Tippen.',
      importPath: '@/motion-arsenal/effects/forms/ValidationPulse',
      usageJsx: '<ValidationPulse springDamping={6} springFreq={9} />',
      props: [
        { key: 'accent', label: 'Error Color', type: 'color', default: '#C93030' },
        { key: 'springDamping', label: 'Damping λ', type: 'range', default: 6, min: 2, max: 14, step: 0.5 },
        { key: 'springFreq', label: 'Freq Hz', type: 'range', default: 9, min: 3, max: 16, step: 0.5 },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./ValidationPulse')),
  },
  {
    meta: {
      id: 'forms-selection-energy-ripple',
      name: 'SelectionEnergyRipple',
      category: 'forms',
      sourceWebsite: 'shopify-editions',
      sourceFiles: ['CoinRain-BMBoDYha.js (ballistische Integration: vel += gravity*dt)', 'KRANK additive Funken'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Gamified Tests (NOX Forge!)', 'Fortschritts-Momente in Funnels'],
      performanceNotes: 'Ripple (CSS) + ≤24 ballistische Funken auf Canvas — günstig.',
      mobileNotes: 'Tap-Punkt = Ripple-Ursprung.',
      reducedMotionNotes: 'Auswahl + Zähler ohne Ripple/Funken.',
      description: 'Auswahl zündet einen Energie-Ripple vom Klickpunkt; Funken-Partikel fliegen mit echter Wurf-Ballistik (Gravitations-Bogen, CoinRain-Integration) zum Fortschritts-Zähler, der beim Einschlag aufblitzt und hochzählt.',
      importPath: '@/motion-arsenal/effects/forms/SelectionEnergyRipple',
      usageJsx: '<SelectionEnergyRipple sparkCount={11} gravity={480} />',
      props: [
        { key: 'accent', label: 'Accent', type: 'color', default: '#C93030' },
        { key: 'sparkCount', label: 'Sparks', type: 'range', default: 11, min: 4, max: 24, step: 1 },
        { key: 'gravity', label: 'Gravity', type: 'range', default: 480, min: 200, max: 900, step: 20 },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./SelectionEnergyRipple')),
  },
];
