import { lazy } from 'react';
import type { EffectEntry } from '../../types';

export const SHOWCASE_CATALOG: EffectEntry[] = [
  {
    meta: {
      id: 'premium-bento-hover-showcase',
      name: 'NoxBentoShowcase',
      displayName: 'NOX Bento Hover Showcase',
      category: 'premium',
      sourceWebsite: 'nox-original',
      sourceFiles: ['NOX original production component'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Service-Übersichten', 'Portfolio-Showcases', 'AI-Growth-Erklärungen', 'Premium Angebotssektionen'],
      performanceNotes: 'DOM/CSS-only. Hover und Fokus verändern ausschließlich Transform, Filter und Opacity. Keine Canvas-, WebGL- oder rAF-Kosten.',
      mobileNotes: 'Das Bento-Grid fällt auf eine vertikale Kartenfolge zurück; Inhalte bleiben per Tap und Tastatur aktivierbar.',
      reducedMotionNotes: 'Scan-, Zoom- und Lift-Transitions werden vollständig deaktiviert; aktive Zustände und Inhalte bleiben sichtbar.',
      description: 'Produktionsfähiges Bento-Showcase mit Services-, Portfolio- und AI-Growth-Presets, Custom-Items, Fokussteuerung und optionalem Spotlight.',
      importPath: '@/motion-arsenal/effects/premium/NoxBentoShowcase',
      usageJsx: '<NoxBentoShowcase variant="services" spotlight showMetrics />',
      props: [
        { key: 'variant', label: 'Showcase Preset', type: 'select', default: 'services', options: ['services', 'portfolio', 'ai-growth'] },
        { key: 'spotlight', label: 'Spotlight', type: 'boolean', default: true },
        { key: 'showMetrics', label: 'Metrics', type: 'boolean', default: true },
      ],
      improvementStatus: 'improved',
      lastImprovedAt: '2026-07-31T10:28:00.000Z',
      lastImprovedBy: 'foundry-live',
      improvementVersion: '1.0.0',
      improvementChangelog: [
        'Added a reusable production bento showcase for services, portfolio work, and AI-growth narratives.',
        'Added custom item support, keyboard and focus activation, optional metrics, and a lightweight spotlight treatment.',
        'Added mobile stack fallback and complete reduced-motion handling without runtime dependencies.',
      ],
      productionSafe: true,
      fullBleed: true,
    },
    Component: lazy(() => import('./NoxBentoShowcase')),
  },
  {
    meta: {
      id: 'premium-image-hover-lens',
      name: 'NoxImageHoverLens',
      displayName: 'NOX Image Hover Lens',
      category: 'premium',
      sourceWebsite: 'nox-original',
      sourceFiles: ['NOX original production component'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Produktdetailseiten', 'Architektur- und Interior-Websites', 'Restaurant- und Food-Websites', 'Premium Bild-Highlights'],
      performanceNotes: 'DOM/CSS-only. Pointer-State aktualisiert nur CSS Custom Properties für Lens-Position und Hintergrund. Keine Canvas-, WebGL- oder dauerhafte Animationsschleife.',
      mobileNotes: 'Tap-and-hold aktiviert die Linse; Größe wird viewport-sicher begrenzt und der Content stapelt sich einspaltig.',
      reducedMotionNotes: 'Zoom- und Lens-Transitions werden deaktiviert; der Detailbereich bleibt sofort nutzbar.',
      description: 'Produktionsfähige Bildlupe mit Produkt-, Architektur- und Food-Presets, Custom-Image, Touch-Aktivierung und steuerbarer Zoom-/Lens-Größe.',
      importPath: '@/motion-arsenal/effects/premium/NoxImageHoverLens',
      usageJsx: '<NoxImageHoverLens variant="product-detail" zoom={2.1} lensSize={180} showHint />',
      props: [
        { key: 'variant', label: 'Image Preset', type: 'select', default: 'product-detail', options: ['product-detail', 'architecture', 'food'] },
        { key: 'zoom', label: 'Zoom', type: 'range', default: 2.1, min: 1.2, max: 4, step: 0.1 },
        { key: 'lensSize', label: 'Lens Size', type: 'range', default: 180, min: 100, max: 280, step: 10 },
        { key: 'showHint', label: 'Hint', type: 'boolean', default: true },
      ],
      improvementStatus: 'improved',
      lastImprovedAt: '2026-07-31T10:29:00.000Z',
      lastImprovedBy: 'foundry-live',
      improvementVersion: '1.0.0',
      improvementChangelog: [
        'Added a reusable production image inspection effect for product, architecture, hospitality, and artisan websites.',
        'Added configurable zoom and lens sizing, custom images and alt text, focus styling, and touch activation.',
        'Added mobile-safe sizing and complete reduced-motion behavior without Canvas, WebGL, or runtime dependencies.',
      ],
      productionSafe: true,
      fullBleed: true,
    },
    Component: lazy(() => import('./NoxImageHoverLens')),
  },
];
