import { lazy } from 'react';
import type { EffectEntry } from '../../types';

export const SOCIAL_PROOF_CATALOG: EffectEntry[] = [
  {
    meta: {
      id: 'premium-testimonial-slider',
      name: 'NoxTestimonialSlider',
      displayName: 'NOX Testimonial Slider',
      category: 'premium',
      sourceWebsite: 'nox-original',
      sourceFiles: ['NOX original production component'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Kundenstimmen', 'Review-Sektionen', 'Case-Study-Abschlüsse', 'Landingpages', 'Hospitality- und Local-Business-Websites'],
      performanceNotes: 'DOM/CSS-only. Autoplay nutzt nur ein pausierbares Interval; keine Canvas-, WebGL- oder dauerhafte rAF-Schleife.',
      mobileNotes: 'Touch-Swipe ab 42px, gestapelte Autor- und Metric-Anzeige sowie große Navigationsziele.',
      reducedMotionNotes: 'Slide-Transitionen werden deaktiviert; Navigation, Autoplay-Pause und Inhalte bleiben vollständig nutzbar.',
      description: 'Produktionsfähiger Testimonial- und Review-Slider mit Custom-Items, drei Branchen-Presets, Rating, Ergebnis-Metric, Tastatursteuerung, Swipe und pausierbarem Autoplay.',
      importPath: '@/motion-arsenal/effects/premium/NoxTestimonialSlider',
      usageJsx: '<NoxTestimonialSlider variant="nox-clients" autoplay showRating showMetric />',
      props: [
        { key: 'variant', label: 'Review Preset', type: 'select', default: 'nox-clients', options: ['nox-clients', 'local-business', 'hospitality'] },
        { key: 'autoplay', label: 'Autoplay', type: 'boolean', default: true },
        { key: 'autoplayDelay', label: 'Autoplay Delay', type: 'range', default: 5600, min: 2600, max: 10000, step: 200 },
        { key: 'showRating', label: 'Rating', type: 'boolean', default: true },
        { key: 'showMetric', label: 'Metric', type: 'boolean', default: true },
      ],
      improvementStatus: 'improved',
      lastImprovedAt: '2026-07-31T10:20:00.000Z',
      lastImprovedBy: 'foundry-live',
      improvementVersion: '1.0.0',
      improvementChangelog: [
        'Added a reusable testimonial and review slider with NOX, local-business, and hospitality presets.',
        'Added custom testimonial data, rating and metric display, keyboard navigation, touch swipe, and pause-on-interaction autoplay.',
        'Added responsive author layouts and complete reduced-motion behavior without runtime dependencies.',
      ],
      productionSafe: true,
      fullBleed: true,
    },
    Component: lazy(() => import('./NoxTestimonialSlider')),
  },
  {
    meta: {
      id: 'premium-metric-proof-strip',
      name: 'NoxMetricProofStrip',
      displayName: 'NOX Metric Proof Strip',
      category: 'premium',
      sourceWebsite: 'nox-original',
      sourceFiles: ['NOX original production component'],
      mode: 'nox-adapted',
      complexity: 'low',
      dependencies: [],
      bestFor: ['Ergebnis-Sektionen', 'Case-Study-Metriken', 'Social Proof', 'Landingpage-Zwischenblöcke', 'Angebots- und Conversion-Seiten'],
      performanceNotes: 'Ein kurzer requestAnimationFrame-Count-up startet nur einmal beim Sichtbarwerden und beendet sich nach der konfigurierten Dauer. Danach 0 Laufzeitkosten.',
      mobileNotes: 'Vier Spalten fallen auf ein 2×2-Grid zurück; lange Details werden auf sehr kleinen Screens ausgeblendet.',
      reducedMotionNotes: 'Metriken springen sofort auf den Endwert; Layout und Inhalte bleiben unverändert.',
      description: 'Produktionsfähiger Ergebnis- und Kennzahlenstreifen mit Custom-Metriken, drei Branchen-Presets, einmaligem Viewport-Count-up, Compact-Modus und Reduced-Motion-Endzustand.',
      importPath: '@/motion-arsenal/effects/premium/NoxMetricProofStrip',
      usageJsx: '<NoxMetricProofStrip variant="growth" duration={1200} showDetails />',
      props: [
        { key: 'variant', label: 'Metric Preset', type: 'select', default: 'growth', options: ['growth', 'local-business', 'hospitality'] },
        { key: 'duration', label: 'Count Duration', type: 'range', default: 1200, min: 300, max: 3000, step: 100 },
        { key: 'showDetails', label: 'Details', type: 'boolean', default: true },
        { key: 'compact', label: 'Compact', type: 'boolean', default: false },
      ],
      improvementStatus: 'improved',
      lastImprovedAt: '2026-07-31T10:21:00.000Z',
      lastImprovedBy: 'foundry-live',
      improvementVersion: '1.0.0',
      improvementChangelog: [
        'Added a reusable metric proof strip with growth, local-business, and hospitality presets.',
        'Added custom metric data, compact mode, responsive 2×2 fallback, and one-shot viewport count-up.',
        'Added immediate reduced-motion end state and zero ongoing animation cost after completion.',
      ],
      productionSafe: true,
      fullBleed: true,
    },
    Component: lazy(() => import('./NoxMetricProofStrip')),
  },
];
