import { lazy } from 'react';
import type { EffectEntry } from '../../types';

export const SCROLL_CATALOG: EffectEntry[] = [
  {
    meta: {
      id: 'scroll-pinned-product-stage',
      name: 'PinnedProductStage',
      displayName: 'Product Stage Variant System',
      category: 'scroll',
      sourceWebsite: 'shopify-editions',
      sourceFiles: [
        'Shopify Szenen-Mechanik (Theatre.js: scroll → Timeline-Frame)',
        'PinnedProductStageVariants.tsx (NOX preset registry)',
        'public/agent-manifests/pinned-product-stage-variants.json',
      ],
      mode: 'nox-adapted',
      complexity: 'high',
      dependencies: [],
      bestFor: ['NOX Produktpräsentationen', 'High-Ticket-Angebote', 'Agenten-Systeme', 'Kunden-Landingpages'],
      performanceNotes: 'Eine sticky Stage, transform-basierte Produkt-Layer und ein gedämpfter rAF-Loop. Preset-Wechsel lädt keine zusätzlichen Runtime-Abhängigkeiten.',
      mobileNotes: 'Touch-Scroll, horizontale Preset-Auswahl und kompakter Content-Stack sind integriert.',
      reducedMotionNotes: 'Zeigt den finalen Produktzustand statisch; Presets und Referenzcodes bleiben bedienbar.',
      description: 'Referenzierbares Produkt-Story-System mit fünf fertigen NOX-Presets. Jede Variante besitzt eigene Kapitel, Module, Kennzahlen, CTA und eine stabile Agenten-Referenz für den späteren Einbau in NOX- oder Kundenwebseiten.',
      currentUsage: ['NOX Labs Produktpräsentation', 'Project-X Agentenzentrale', 'zukünftige Kundenwebseiten'],
      technicalBasis: 'Sticky scroll timeline + CSS-3D layers + deterministic glyph + exported preset registry + public agent manifest.',
      importPath: '@/motion-arsenal/effects/scroll/PinnedProductStageVariants',
      usageJsx: '<PinnedProductStage variant="nox-global-sales-os" showVariantSwitcher />',
      props: [
        {
          key: 'variant',
          label: 'Product Variant',
          type: 'select',
          default: 'nox-global-sales-os',
          options: [
            'nox-global-sales-os',
            'project-x-command-center',
            'ai-growth-engine',
            'conversion-website-system',
            'automation-ops-system',
          ],
          group: 'Content',
        },
        { key: 'showVariantSwitcher', label: 'Show Variant Switcher', type: 'boolean', default: true, group: 'Content' },
        { key: 'damping', label: 'Damping', type: 'range', default: 8, min: 2, max: 16, step: 1, group: 'Motion' },
        { key: 'rotatePerSection', label: 'Rotate/Section', type: 'range', default: 90, min: 20, max: 180, step: 10, group: 'Motion' },
        { key: 'scalePulse', label: 'Scale Pulse', type: 'range', default: 0.18, min: 0, max: 0.4, step: 0.05, group: 'Motion' },
        { key: 'colorShift', label: 'Color Shift', type: 'boolean', default: true, group: 'Motion' },
      ],
      productionSafe: true,
      status: 'production-safe',
    },
    Component: lazy(() => import('./PinnedProductStageVariants')),
  },
  {
    meta: {
      id: 'scroll-object-transform',
      name: 'ScrollObjectTransform',
      category: 'scroll',
      sourceWebsite: 'shopify-editions',
      sourceFiles: ['Shopify Theatre.js-Keyframe-Stationen', 'KRANK smoothstep-Mapping'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Scroll-Stories', 'Prozess-Erklärungen mit wanderndem Objekt'],
      performanceNotes: 'Ein Objekt-Transform pro Frame, smoothstep zwischen Stationen — günstig.',
      mobileNotes: 'Touch-tauglich.',
      reducedMotionNotes: 'Objekt an letzter Station, statisch.',
      description: 'Ein Objekt wandert scroll-getrieben durch klare Keyframe-Stationen (Position, Rotation, Morph via border-radius) mit smoothstep-Interpolation — Timeline-Keyframes wie in Theatre.js, ohne Library.',
      importPath: '@/motion-arsenal/effects/scroll/ScrollObjectTransform',
      usageJsx: '<ScrollObjectTransform stations={4} spin={1} morph={0.8} />',
      props: [
        { key: 'stations', label: 'Stations', type: 'range', default: 4, min: 2, max: 6, step: 1 },
        { key: 'damping', label: 'Damping', type: 'range', default: 8, min: 2, max: 16, step: 1 },
        { key: 'spin', label: 'Spin', type: 'range', default: 1, min: 0, max: 3, step: 0.1 },
        { key: 'morph', label: 'Morph', type: 'range', default: 0.8, min: 0, max: 1, step: 0.05 },
        { key: 'showRail', label: 'Station Rail', type: 'boolean', default: true },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./ScrollObjectTransform')),
  },
  {
    meta: {
      id: 'scroll-parallax-symbol-layers',
      name: 'ParallaxSymbolLayers',
      category: 'scroll',
      sourceWebsite: 'oryzo-screenshot',
      sourceFiles: ['ORYZO Tiefenstaffelung (Scroll-Variante)', 'KRANK Layering (eine Physik-Quelle)'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Content-Seiten mit Tiefe', 'Über-uns/Story-Sektionen'],
      performanceNotes: '3-4 transform-Layer, damped — günstig. Blur nur auf tiefster Ebene.',
      mobileNotes: 'Touch-tauglich; travel ≤ 0.8 auf Mobile.',
      reducedMotionNotes: 'Layer statisch versetzt (Tiefe bleibt sichtbar).',
      description: 'Drei bis vier Tiefenebenen aus prozeduralen Glyphen/Symbolen scrollen mit unterschiedlichen Geschwindigkeiten und Blur-Staffelung — die ORYZO-Tiefe als Scroll-Choreografie.',
      importPath: '@/motion-arsenal/effects/scroll/ParallaxSymbolLayers',
      usageJsx: '<ParallaxSymbolLayers layers={4} travel={0.8} colorMode="nox" />',
      props: [
        { key: 'layers', label: 'Layers', type: 'range', default: 4, min: 3, max: 4, step: 1 },
        { key: 'travel', label: 'Travel', type: 'range', default: 0.8, min: 0.3, max: 1.2, step: 0.05 },
        { key: 'blurMax', label: 'Max Blur', type: 'range', default: 5, min: 0, max: 10, step: 0.5 },
        { key: 'damping', label: 'Damping', type: 'range', default: 8, min: 2, max: 16, step: 1 },
        { key: 'colorMode', label: 'Colors', type: 'select', default: 'nox', options: ['nox', 'ember', 'mono'] },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./ParallaxSymbolLayers')),
  },
  {
    meta: {
      id: 'scroll-timeline-progress-rail',
      name: 'TimelineProgressRail',
      category: 'scroll',
      sourceWebsite: 'nox-original',
      sourceFiles: ['KRANK stroke-dash Draw (Checkmarks)', 'Lenis-damped Progress (shopify_editions.md)'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Prozess-/Roadmap-Sektionen', 'Onboarding-Strecken', 'NOX Forge Protokoll-Ansicht'],
      performanceNotes: 'Eine Progress-Linie + N Meilenstein-Nodes — günstig.',
      mobileNotes: 'Touch-tauglich.',
      reducedMotionNotes: 'Rail komplett gefüllt, alle Nodes gezündet.',
      description: 'Vertikale Timeline: die Progress-Linie füllt mit gedämpftem Scroll, Meilenstein-Nodes zünden nacheinander mit Glow-Puls und Checkmark-Draw, der aktive Abschnitt hebt sich.',
      importPath: '@/motion-arsenal/effects/scroll/TimelineProgressRail',
      usageJsx: '<TimelineProgressRail milestones={5} glow={0.8} />',
      props: [
        { key: 'milestones', label: 'Milestones', type: 'range', default: 5, min: 3, max: 6, step: 1 },
        { key: 'damping', label: 'Damping', type: 'range', default: 8, min: 2, max: 16, step: 1 },
        { key: 'glow', label: 'Glow', type: 'range', default: 0.8, min: 0, max: 1, step: 0.05 },
        { key: 'accent', label: 'Accent', type: 'color', default: '#C93030' },
        { key: 'showPercent', label: 'Percent', type: 'boolean', default: true },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./TimelineProgressRail')),
  },
  {
    meta: {
      id: 'scroll-velocity-skew',
      name: 'ScrollVelocitySkew',
      category: 'scroll',
      sourceWebsite: 'krank-lusion',
      sourceFiles: ['KRANK/src/hoisted.js (SecondOrderDynamics: velocity accumulation → damping 8-15)'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Editorial-/Fashion-Feel', 'Marquee-lastige Seiten', 'Portfolio'],
      performanceNotes: 'Velocity-Ableitung + transform/blur auf einem Container + Marquee-Offsets — günstig; blur nur bei aktiver Bewegung.',
      mobileNotes: 'Touch-Scroll erzeugt dieselbe Velocity — funktioniert.',
      reducedMotionNotes: 'Keine Skew/Marquee-Reaktion, statischer Content.',
      description: 'Der Inhalt reagiert auf Scroll-GESCHWINDIGKEIT statt Position: skewY, Letter-Spacing und Blur wachsen mit der Velocity und federn gedämpft zurück; Marquee-Zeilen beschleunigen mit.',
      importPath: '@/motion-arsenal/effects/scroll/ScrollVelocitySkew',
      usageJsx: '<ScrollVelocitySkew skewMax={10} damping={9} />',
      props: [
        { key: 'skewMax', label: 'Skew Max °', type: 'range', default: 10, min: 2, max: 20, step: 1 },
        { key: 'damping', label: 'Damping', type: 'range', default: 9, min: 3, max: 16, step: 1 },
        { key: 'marqueeBase', label: 'Marquee px/s', type: 'range', default: 40, min: 0, max: 120, step: 5 },
        { key: 'accent', label: 'Accent', type: 'color', default: '#C93030' },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./ScrollVelocitySkew')),
  },
  {
    meta: {
      id: 'scroll-section-snap-depth',
      name: 'SectionSnapDepth',
      category: 'scroll',
      sourceWebsite: 'shopify-editions',
      sourceFiles: ['RiveInner (IntersectionObserver Lazy-Aktivierung)', 'Nav-Cascade-Timing'],
      mode: 'nox-adapted',
      complexity: 'medium',
      dependencies: [],
      bestFor: ['Fullscreen-Story-Seiten', 'Pitch-/Launch-Pages', 'NOX Forge Phasen-Erklärung'],
      performanceNotes: 'CSS scroll-snap + IntersectionObserver — kein rAF-Loop.',
      mobileNotes: 'scroll-snap ist mobiles Kern-Pattern — sehr gut.',
      reducedMotionNotes: 'Kein Snap-Zwang, alle Sektionen im Endzustand.',
      description: 'Sektionen snappen (CSS scroll-snap); die aktive baut sich mit Tiefen-Stagger auf (scale 0.94→1 + Layer-Cascade), inaktive dimmen und blurren weg — Fokus-Tiefe wie eine Kamera.',
      importPath: '@/motion-arsenal/effects/scroll/SectionSnapDepth',
      usageJsx: '<SectionSnapDepth sectionCount={4} dimStrength={0.7} />',
      props: [
        { key: 'sectionCount', label: 'Sections', type: 'range', default: 4, min: 2, max: 5, step: 1 },
        { key: 'dimStrength', label: 'Dim', type: 'range', default: 0.7, min: 0.2, max: 1, step: 0.05 },
        { key: 'accent', label: 'Accent', type: 'color', default: '#C93030' },
      ],
      productionSafe: true,
    },
    Component: lazy(() => import('./SectionSnapDepth')),
  },
];